/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Encrypt.CryptoUtils;
import MD5.Checksum;
import UDP.UDP;
import java.io.File;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Nguyen Hoang Thong
 */
public class receivePanel extends javax.swing.JPanel {

    /**
     * Creates new form receivePanel
     */
    static UDP udp = new UDP();
    File file;
    String s1;
    Checksum checksum = new Checksum();
    public receivePanel() {
        initComponents();
       // Thread thread = new Thread(new receivePanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPath = new javax.swing.JTextField();
        tfRec = new javax.swing.JTextField();
        btnBrowserRec = new javax.swing.JButton();
        btnOKRec = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("File path");

        jLabel3.setText("MD5 ");

        btnBrowserRec.setText("Browser");
        btnBrowserRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserRecActionPerformed(evt);
            }
        });

        btnOKRec.setText("OK");
        btnOKRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKRecActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowserRec))
                            .addComponent(tfRec, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnOKRec, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(53, 53, 53)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowserRec))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnOKRec))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBrowserRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserRecActionPerformed
        // TODO add your handling code here:
        int select = jFileChooser1.showSaveDialog(this);
        if(select == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                file = jFileChooser1.getSelectedFile();
                tfPath.setText(file.getName().toString());
               // udp.receiveUDP(file);
                
            }
            catch(Exception ex)
            {
                        
            }
        }
    }//GEN-LAST:event_btnBrowserRecActionPerformed

    private void btnOKRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKRecActionPerformed
        try
        {
            // TODO add your handling code here:
            System.out.println("save yet");
            //     System.out.println(s.toString());
            File encrypt = new File("Encrypt1.encrypt");
            s1= new String(udp.receiveUDP(encrypt).toString());
            
            String key ="nguyenhoangthong";
            try
            {
                CryptoUtils.decrypt(key, encrypt,file);
                
            }
            catch(Exception e)
            {
                System.err.println(e.getMessage().toString());
                
            }
            String cs = new String(checksum.MD5(file).toString());
            System.err.println("receive "+s1);
            System.out.println("client "+cs);
            //tfSend.setText(s1);
            tfRec.setText(cs);
            checksum.ghiFile(file.getName()+".txt","Hash MD5 file nhan duoc: "+ s1 +"\r\n");
            checksum.ghiFile(file.getName()+".txt","Hash MD5 file da luu : "+ cs+"\r\n");
//            if( (cs.equalsIgnoreCase(s1)))
//            {
//                tfDialog.setText("truyen file thanh cong");
//            }
            
            
        }
        catch(NoSuchAlgorithmException ex)
        {
            Logger.getLogger(receivePanel.class.getName()).log(Level.SEVERE, null, ex);
           // tfDialog.setText("nhan file khong thanh cong");
        } catch (IOException ex) {
            Logger.getLogger(receivePanel.class.getName()).log(Level.SEVERE, null, ex);
           // tfDialog.setText("nhan file khong thanh cong");
        }
              
        
    }//GEN-LAST:event_btnOKRecActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowserRec;
    private javax.swing.JButton btnOKRec;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfPath;
    private javax.swing.JTextField tfRec;
    // End of variables declaration//GEN-END:variables

    

   // @Override
//    public void run() {
//        s = udp.receiveUDP(file);
//        tfDialog.setText(s.toString());
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
